import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying DEADLOCK Protocol contracts...");
  console.log("Deployer:", deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Balance:", ethers.formatEther(balance), "FIL");

  if (balance === 0n) {
    console.warn("WARNING: Deployer has no balance. Get testnet FIL from:");
    console.warn("  https://faucet.calibnet.chainsafe-fil.io/funds.html");
    process.exit(1);
  }

  // ─── Deploy DeadlockRegistry ───────────────────────────────────────────────
  console.log("\n[1/3] Deploying DeadlockRegistry...");
  const DeadlockRegistry = await ethers.getContractFactory("DeadlockRegistry");
  const registry = await DeadlockRegistry.deploy(deployer.address);
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();
  console.log("  DeadlockRegistry deployed to:", registryAddress);

  // ─── Deploy DeadlockWitnessNFT ────────────────────────────────────────────
  console.log("\n[2/3] Deploying DeadlockWitnessNFT...");
  const DeadlockWitnessNFT = await ethers.getContractFactory("DeadlockWitnessNFT");
  const witnessNFT = await DeadlockWitnessNFT.deploy(registryAddress);
  await witnessNFT.waitForDeployment();
  const witnessNFTAddress = await witnessNFT.getAddress();
  console.log("  DeadlockWitnessNFT deployed to:", witnessNFTAddress);

  // ─── Deploy DeadlockHypercert ─────────────────────────────────────────────
  console.log("\n[3/3] Deploying DeadlockHypercert...");
  const DeadlockHypercert = await ethers.getContractFactory("DeadlockHypercert");
  const hypercert = await DeadlockHypercert.deploy(registryAddress);
  await hypercert.waitForDeployment();
  const hypercertAddress = await hypercert.getAddress();
  console.log("  DeadlockHypercert deployed to:", hypercertAddress);

  // ─── Output Deployment Addresses ──────────────────────────────────────────
  const deploymentInfo = {
    network: "calibration",
    chainId: 314159,
    deployer: deployer.address,
    deployedAt: new Date().toISOString(),
    contracts: {
      DeadlockRegistry: registryAddress,
      DeadlockWitnessNFT: witnessNFTAddress,
      DeadlockHypercert: hypercertAddress,
    },
  };

  console.log("\n✅ Deployment complete!");
  console.log("\nContract Addresses:");
  console.log("  NEXT_PUBLIC_REGISTRY_ADDRESS=", registryAddress);
  console.log("  NEXT_PUBLIC_WITNESS_NFT_ADDRESS=", witnessNFTAddress);
  console.log("  NEXT_PUBLIC_HYPERCERT_ADDRESS=", hypercertAddress);

  // Save to file
  const outputPath = path.join(__dirname, "../deployments.json");
  fs.writeFileSync(outputPath, JSON.stringify(deploymentInfo, null, 2));
  console.log("\nDeployment info saved to:", outputPath);

  // Also write addresses file for frontend
  const frontendAddressesPath = path.join(__dirname, "../../frontend/src/lib/contracts/addresses.ts");
  if (fs.existsSync(path.dirname(frontendAddressesPath))) {
    const addressesContent = `// Auto-generated by deploy.ts — do not edit manually
// Deployed: ${new Date().toISOString()}

export const CONTRACT_ADDRESSES = {
  REGISTRY: "${registryAddress}" as const,
  WITNESS_NFT: "${witnessNFTAddress}" as const,
  HYPERCERT: "${hypercertAddress}" as const,
} as const;
`;
    fs.writeFileSync(frontendAddressesPath, addressesContent);
    console.log("Frontend addresses file updated.");
  }

  console.log("\nView on explorer:");
  console.log(`  Registry: https://calibration.filscan.io/address/${registryAddress}`);
  console.log(`  WitnessNFT: https://calibration.filscan.io/address/${witnessNFTAddress}`);
  console.log(`  Hypercert: https://calibration.filscan.io/address/${hypercertAddress}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
